Search.appendIndex(
    [
                {
            "fqsen": "\\NWiki\\Cli",
            "name": "Cli",
            "summary": "Main\u0020CLI\u0020implementation",
            "url": "classes/NWiki-Cli.html"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003ArelativePath\u0028\u0029",
            "name": "relativePath",
            "summary": "Given\u0020two\u0020paths,\u0020calculate\u0020the\u0020relative\u0020path\u0020from\u0020one\u0020to\u0020the\u0020other",
            "url": "classes/NWiki-Cli.html#method_relativePath"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003Astderr\u0028\u0029",
            "name": "stderr",
            "summary": "output\u0020message\u0020to\u0020stderr",
            "url": "classes/NWiki-Cli.html#method_stderr"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003Ahelp\u0028\u0029",
            "name": "help",
            "summary": "Show\u0020this\u0020help",
            "url": "classes/NWiki-Cli.html#method_help"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003Aplugins\u0028\u0029",
            "name": "plugins",
            "summary": "List\u0020available\u0020plugins",
            "url": "classes/NWiki-Cli.html#method_plugins"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003Ainstall\u0028\u0029",
            "name": "install",
            "summary": "Install\u0020assets",
            "url": "classes/NWiki-Cli.html#method_install"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/NWiki-Cli.html#method_load"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003ATRC",
            "name": "TRC",
            "summary": "Used\u0020by\u0020stderr\u0020to\u0020make\u0020it\u0020report\u0020caller\u0020traceback\u0020info",
            "url": "classes/NWiki-Cli.html#constant_TRC"
        },                {
            "fqsen": "\\NWiki\\Cli\u003A\u003ANONL",
            "name": "NONL",
            "summary": "Used\u0020by\u0020stderr\u0020to\u0020prevent\u0020printing\u0020of\u0020a\u0020New\u0020line\u0020at\u0020the\u0020end",
            "url": "classes/NWiki-Cli.html#constant_NONL"
        },                {
            "fqsen": "\\NWiki\\Core",
            "name": "Core",
            "summary": "Main\u0020NacoWiki\u0020functionality",
            "url": "classes/NWiki-Core.html"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AprunePath\u0028\u0029",
            "name": "prunePath",
            "summary": "When\u0020a\u0020file\/directory\u0020is\u0020deleted,\u0020make\u0020sure\u0020no\u0020empty\u0020dirs\u0020remain",
            "url": "classes/NWiki-Core.html#method_prunePath"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AmakePath\u0028\u0029",
            "name": "makePath",
            "summary": "Make\u0020sure\u0020a\u0020directory\u0020\u0028and\u0020parent\u0020directories\u0020in\u0020between\u0029\u0020exist",
            "url": "classes/NWiki-Core.html#method_makePath"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AcodeMirror\u0028\u0029",
            "name": "codeMirror",
            "summary": "Show\u0020a\u0020CodeMirror\u0020editor\u0020web\u0020view",
            "url": "classes/NWiki-Core.html#method_codeMirror"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AfolderContents\u0028\u0029",
            "name": "folderContents",
            "summary": "Get\u0020the\u0020contents\u0020of\u0020a\u0020folder",
            "url": "classes/NWiki-Core.html#method_folderContents"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Implements\u0020search\u0020functionality",
            "url": "classes/NWiki-Core.html#method_search"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003Atheme\u0028\u0029",
            "name": "theme",
            "summary": "Link\u0020theme\u0020assets",
            "url": "classes/NWiki-Core.html#method_theme"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AreadFolder\u0028\u0029",
            "name": "readFolder",
            "summary": "Show\u0020the\u0020contents\u0020of\u0020a\u0020folder",
            "url": "classes/NWiki-Core.html#method_readFolder"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AsearchPage\u0028\u0029",
            "name": "searchPage",
            "summary": "Search\u0020results\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_searchPage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003ArawPage\u0028\u0029",
            "name": "rawPage",
            "summary": "Raw\u0020page\u0020display",
            "url": "classes/NWiki-Core.html#method_rawPage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003ApreparePayload\u0028\u0029",
            "name": "preparePayload",
            "summary": "Utility\u0020function\u0020to\u0020initialize\u0020a\u0020prepare\u0020payload\u0020event\u0020array",
            "url": "classes/NWiki-Core.html#method_preparePayload"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AreadPage\u0028\u0029",
            "name": "readPage",
            "summary": "Read\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_readPage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AmissingPage\u0028\u0029",
            "name": "missingPage",
            "summary": "Missing\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_missingPage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AdeletePage\u0028\u0029",
            "name": "deletePage",
            "summary": "delete\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_deletePage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003ArenamePage\u0028\u0029",
            "name": "renamePage",
            "summary": "rename\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_renamePage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AeditPage\u0028\u0029",
            "name": "editPage",
            "summary": "edit\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_editPage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AsavePage\u0028\u0029",
            "name": "savePage",
            "summary": "save\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_savePage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AattachToPage\u0028\u0029",
            "name": "attachToPage",
            "summary": "attach\u0020to\u0020page\u0020event\u0020handler",
            "url": "classes/NWiki-Core.html#method_attachToPage"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AapiPageList\u0028\u0029",
            "name": "apiPageList",
            "summary": "Returns\u0020a\u0020page\u0020list",
            "url": "classes/NWiki-Core.html#method_apiPageList"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/NWiki-Core.html#method_load"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003ACODEMIRROR",
            "name": "CODEMIRROR",
            "summary": "URL\u0020to\u0020the\u0020supported\u0020CODEMIRROR\u0020version",
            "url": "classes/NWiki-Core.html#constant_CODEMIRROR"
        },                {
            "fqsen": "\\NWiki\\Core\u003A\u003AHIGHLIGHT_JS",
            "name": "HIGHLIGHT_JS",
            "summary": "URL\u0020to\u0020the\u0020supported\u0020HIGHLIGHT_JS\u0020version",
            "url": "classes/NWiki-Core.html#constant_HIGHLIGHT_JS"
        },                {
            "fqsen": "\\NWiki\\PluginCollection",
            "name": "PluginCollection",
            "summary": "Plugin\u0020management",
            "url": "classes/NWiki-PluginCollection.html"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003ApluginPath\u0028\u0029",
            "name": "pluginPath",
            "summary": "translates\u0020configured\u0020plugin\u0020path\u0020into\u0020list\u0020of\u0020directories",
            "url": "classes/NWiki-PluginCollection.html#method_pluginPath"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "Return\u0020the\u0020file\u0020path\u0020to\u0020the\u0020a\u0020Plugin\u0020source",
            "url": "classes/NWiki-PluginCollection.html#method_path"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AapiError\u0028\u0029",
            "name": "apiError",
            "summary": "sets\u0020up\u0020a\u0020API\u0020handler\u0020as\u0020returning\u0020an\u0020error.",
            "url": "classes/NWiki-PluginCollection.html#method_apiError"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AloadPlugins\u0028\u0029",
            "name": "loadPlugins",
            "summary": "Load\u0020plugins\u0020in\u0020plugin\u0020paths",
            "url": "classes/NWiki-PluginCollection.html#method_loadPlugins"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003Aautoload\u0028\u0029",
            "name": "autoload",
            "summary": "Autoload\u0020event\u0020handlers",
            "url": "classes/NWiki-PluginCollection.html#method_autoload"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003Adevt\u0028\u0029",
            "name": "devt",
            "summary": "Utility\u0020function\u0020to\u0020send\u0020read\u002Donly\u0020events",
            "url": "classes/NWiki-PluginCollection.html#method_devt"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AregisterEvent\u0028\u0029",
            "name": "registerEvent",
            "summary": "Register\u0020an\u0020event\u0020handler",
            "url": "classes/NWiki-PluginCollection.html#method_registerEvent"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AdispatchEvent\u0028\u0029",
            "name": "dispatchEvent",
            "summary": "Dispatch\u0020events",
            "url": "classes/NWiki-PluginCollection.html#method_dispatchEvent"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AregisterMedia\u0028\u0029",
            "name": "registerMedia",
            "summary": "Register\u0020a\u0020new\u0020media\u0020type",
            "url": "classes/NWiki-PluginCollection.html#method_registerMedia"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AmediaExt\u0028\u0029",
            "name": "mediaExt",
            "summary": "Check\u0020the\u0020media\u0020handler\u0020for\u0020the\u0020page",
            "url": "classes/NWiki-PluginCollection.html#method_mediaExt"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AOK",
            "name": "OK",
            "summary": "Event\u0020handler\u0020return\u0020code\u0020indicating\u0020that\u0020event\u0020was\u0020handled.",
            "url": "classes/NWiki-PluginCollection.html#constant_OK"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AOKSTOP",
            "name": "OKSTOP",
            "summary": "Event\u0020handler\u0020return\u0020code\u0020indicating\u0020that\u0020event\u0020was\u0020handled\u0020and\u0020event\nprocessing\u0020should\u0020be\u0020stopped.",
            "url": "classes/NWiki-PluginCollection.html#constant_OKSTOP"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003ANOOP",
            "name": "NOOP",
            "summary": "Event\u0020handler\u0020return\u0020code\u0020indicating\u0020that\u0020event\u0020was\u0020\u002A\u002ANOT\u002A\u002A\u0020handled.",
            "url": "classes/NWiki-PluginCollection.html#constant_NOOP"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AAPI_OK",
            "name": "API_OK",
            "summary": "API\u0020Event\u0020handler\u0020status\u0020code\u0020indicating\u0020succesful\u0020execution",
            "url": "classes/NWiki-PluginCollection.html#constant_API_OK"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003AAPI_ERROR",
            "name": "API_ERROR",
            "summary": "API\u0020Event\u0020handler\u0020status\u0020code\u0020indicating\u0020execution\u0020failure",
            "url": "classes/NWiki-PluginCollection.html#constant_API_ERROR"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "List\u0020of\u0020event\u0020hanlders",
            "url": "classes/NWiki-PluginCollection.html#property_handlers"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003A\u0024mediatypes",
            "name": "mediatypes",
            "summary": "Used\u0020to\u0020quickly\u0020identified\u0020registered\u0020handlers",
            "url": "classes/NWiki-PluginCollection.html#property_mediatypes"
        },                {
            "fqsen": "\\NWiki\\PluginCollection\u003A\u003A\u0024plugins",
            "name": "plugins",
            "summary": "List\u0020of\u0020loaded\u0020plugins",
            "url": "classes/NWiki-PluginCollection.html#property_plugins"
        },                {
            "fqsen": "\\NWiki\\Util",
            "name": "Util",
            "summary": "Utility\u0020methods",
            "url": "classes/NWiki-Util.html"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003ArunPath\u0028\u0029",
            "name": "runPath",
            "summary": "resolves\u0020a\u0020file\u0020or\u0020URL\u0020path",
            "url": "classes/NWiki-Util.html#method_runPath"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003Asanitize\u0028\u0029",
            "name": "sanitize",
            "summary": "make\u0020sure\u0020input\u0020path\u0020is\u0020sane",
            "url": "classes/NWiki-Util.html#method_sanitize"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003Avdump\u0028\u0029",
            "name": "vdump",
            "summary": "var_dump\u0020to\u0020string",
            "url": "classes/NWiki-Util.html#method_vdump"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "log\u0020message",
            "url": "classes/NWiki-Util.html#method_log"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AdumpLog\u0028\u0029",
            "name": "dumpLog",
            "summary": "dump\u0020log\u0020messages",
            "url": "classes/NWiki-Util.html#method_dumpLog"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AfileMeta\u0028\u0029",
            "name": "fileMeta",
            "summary": "Generat\u0020file\u002Dsystem\u0020level\u0020meta\u0020data",
            "url": "classes/NWiki-Util.html#method_fileMeta"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AdefaultMeta\u0028\u0029",
            "name": "defaultMeta",
            "summary": "Generate\u0020default\u0020meta\u002Ddata\u0020from\u0020file\u0020system",
            "url": "classes/NWiki-Util.html#method_defaultMeta"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AfileContents\u0028\u0029",
            "name": "fileContents",
            "summary": "cached\u0020file_get_contents",
            "url": "classes/NWiki-Util.html#method_fileContents"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AsendFile\u0028\u0029",
            "name": "sendFile",
            "summary": "Send\u0020\u0024file_path",
            "url": "classes/NWiki-Util.html#method_sendFile"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AwalkTree\u0028\u0029",
            "name": "walkTree",
            "summary": "get\u0020directory\u0020contents",
            "url": "classes/NWiki-Util.html#method_walkTree"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003AVALID_CHARS",
            "name": "VALID_CHARS",
            "summary": "Set\u0020of\u0020valid\u0020characters",
            "url": "classes/NWiki-Util.html#constant_VALID_CHARS"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "content\u0020cache",
            "url": "classes/NWiki-Util.html#property_cache"
        },                {
            "fqsen": "\\NWiki\\Util\u003A\u003A\u0024logmsg",
            "name": "logmsg",
            "summary": "used\u0020to\u0020keep\u0020logged\u0020strings",
            "url": "classes/NWiki-Util.html#property_logmsg"
        },                {
            "fqsen": "\\APP_NAME",
            "name": "APP_NAME",
            "summary": "Canonical\u0020name\u0020of\u0020the\u0020NacoWiki\u0020application",
            "url": "namespaces/default.html#constant_APP_NAME"
        },                {
            "fqsen": "\\APP_URL",
            "name": "APP_URL",
            "summary": "URL\u0020of\u0020the\u0020NacoWiki\u0020application",
            "url": "namespaces/default.html#constant_APP_URL"
        },                {
            "fqsen": "\\APP_VERSION",
            "name": "APP_VERSION",
            "summary": "NacoWiki\u0020Application\u0020version",
            "url": "namespaces/default.html#constant_APP_VERSION"
        },                {
            "fqsen": "\\APP_DIR",
            "name": "APP_DIR",
            "summary": "Current\u0020application\u0020code\u0020directory.",
            "url": "namespaces/default.html#constant_APP_DIR"
        },                {
            "fqsen": "\\EM_NONE",
            "name": "EM_NONE",
            "summary": "Used\u0020by\u0020NacoWikiApp\u003A\u003AerrMsg\u0020to\u0020indicate\u0020that\u0020no\u0020special\u0020processing\u0020is\u0020needed",
            "url": "namespaces/default.html#constant_EM_NONE"
        },                {
            "fqsen": "\\EM_PHPERR",
            "name": "EM_PHPERR",
            "summary": "Used\u0020by\u0020NacoWikiApp\u003A\u003AerrMsg\u0020to\u0020indicate\u0020that\u0020PHP\u0020Error\u0020needs\u0020to\u0020be\u0020displayed",
            "url": "namespaces/default.html#constant_EM_PHPERR"
        },                {
            "fqsen": "\\NacoWikiApp",
            "name": "NacoWikiApp",
            "summary": "Main\u0020Application\u0020class",
            "url": "classes/NacoWikiApp.html"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020NanoWiki\u0020application\u0020instance",
            "url": "classes/NacoWikiApp.html#method___construct"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AfilePath\u0028\u0029",
            "name": "filePath",
            "summary": "Convert\u0020URL\u0020to\u0020an\u0020actual\u0020file\u0020path",
            "url": "classes/NacoWikiApp.html#method_filePath"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AerrMsg\u0028\u0029",
            "name": "errMsg",
            "summary": "Show\u0020a\u0020HTML\u0020error\u0020message\u0020and\u0020dies.",
            "url": "classes/NacoWikiApp.html#method_errMsg"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AisWritable\u0028\u0029",
            "name": "isWritable",
            "summary": "Current\u0020document\u0020is\u0020writable",
            "url": "classes/NacoWikiApp.html#method_isWritable"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AisReadable\u0028\u0029",
            "name": "isReadable",
            "summary": "Current\u0020document\u0020is\u0020readable",
            "url": "classes/NacoWikiApp.html#method_isReadable"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AmkUrl\u0028\u0029",
            "name": "mkUrl",
            "summary": "Create\u0020a\u0020URL\u0020to\u0020the\u0020given\u0020resource.",
            "url": "classes/NacoWikiApp.html#method_mkUrl"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003Aasset\u0028\u0029",
            "name": "asset",
            "summary": "Returns\u0020a\u0020URL\u0020to\u0020an\u0020static\u0020file\u0020asset",
            "url": "classes/NacoWikiApp.html#method_asset"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AassetQS\u0028\u0029",
            "name": "assetQS",
            "summary": "Returns\u0020a\u0020URL\u0020to\u0020an\u0020static\u0020file\u0020asset\u0020with\u0020timestamp",
            "url": "classes/NacoWikiApp.html#method_assetQS"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003Acli\u0028\u0029",
            "name": "cli",
            "summary": "Main\u0020dispatch\u0020point\u0020for\u0020CLI\u0020sub\u002Dcommands",
            "url": "classes/NacoWikiApp.html#method_cli"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Main\u0020application\u0020entry\u0020point\u0020method",
            "url": "classes/NacoWikiApp.html#method_run"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AdeclareContext\u0028\u0029",
            "name": "declareContext",
            "summary": "Declare\u0020a\u0020context\u0020variable.",
            "url": "classes/NacoWikiApp.html#method_declareContext"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003AinitContext\u0028\u0029",
            "name": "initContext",
            "summary": "Initialize\u0020user\u0020context",
            "url": "classes/NacoWikiApp.html#method_initContext"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024cfg",
            "name": "cfg",
            "summary": "Contains\u0020running\u0020app\u0020configuration\u0020\u002A",
            "url": "classes/NacoWikiApp.html#property_cfg"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024page",
            "name": "page",
            "summary": "Current\u0020document",
            "url": "classes/NacoWikiApp.html#property_page"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024meta",
            "name": "meta",
            "summary": "Current\u0020document\u0020meta\u002Ddata",
            "url": "classes/NacoWikiApp.html#property_meta"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024scheme",
            "name": "scheme",
            "summary": "HTTP\u0020context,\u0020should\u0020be\u0020set\u0020to\u0020http\u0020or\u0020https,\u0020otherwise\u0020is\u0020NULL",
            "url": "classes/NacoWikiApp.html#property_scheme"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024remote_addr",
            "name": "remote_addr",
            "summary": "HTTP\u0020client\u0027s\u0020remote\u0020address",
            "url": "classes/NacoWikiApp.html#property_remote_addr"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024http_host",
            "name": "http_host",
            "summary": "HTTP\u0020request\u0020host",
            "url": "classes/NacoWikiApp.html#property_http_host"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024https",
            "name": "https",
            "summary": "TRUE\u0020if\u0020using\u0020https",
            "url": "classes/NacoWikiApp.html#property_https"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024context",
            "name": "context",
            "summary": "Current\u0020user\/session\u0020context",
            "url": "classes/NacoWikiApp.html#property_context"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024ctxvars",
            "name": "ctxvars",
            "summary": "Defined\u0020context\u0020variables",
            "url": "classes/NacoWikiApp.html#property_ctxvars"
        },                {
            "fqsen": "\\NacoWikiApp\u003A\u003A\u0024view",
            "name": "view",
            "summary": "Default\u0020view\u0020class",
            "url": "classes/NacoWikiApp.html#property_view"
        },                {
            "fqsen": "\\PluginCode",
            "name": "PluginCode",
            "summary": "Implements\u0020media\u0020handling\u0020for\u0020programming\u0020source\u0020code",
            "url": "classes/PluginCode.html"
        },                {
            "fqsen": "\\PluginCode\u003A\u003AreadStruct\u0028\u0029",
            "name": "readStruct",
            "summary": "Read\u0020structured\u0020data",
            "url": "classes/PluginCode.html#method_readStruct"
        },                {
            "fqsen": "\\PluginCode\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Edit\u0020event\u0020handler",
            "url": "classes/PluginCode.html#method_edit"
        },                {
            "fqsen": "\\PluginCode\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020event\u0020handler",
            "url": "classes/PluginCode.html#method_render"
        },                {
            "fqsen": "\\PluginCode\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020event\u0020handler",
            "url": "classes/PluginCode.html#method_read"
        },                {
            "fqsen": "\\PluginCode\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginCode.html#method_load"
        },                {
            "fqsen": "\\PluginCode\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/PluginCode.html#constant_VERSION"
        },                {
            "fqsen": "\\PluginCode\u003A\u003ATYPES",
            "name": "TYPES",
            "summary": "",
            "url": "classes/PluginCode.html#constant_TYPES"
        },                {
            "fqsen": "\\PluginEmoji",
            "name": "PluginEmoji",
            "summary": "Emoji\u0020\u30C3\u0020Plugin",
            "url": "classes/PluginEmoji.html"
        },                {
            "fqsen": "\\PluginEmoji\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginEmoji.html#method_load"
        },                {
            "fqsen": "\\PluginEmoji\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/PluginEmoji.html#constant_VERSION"
        },                {
            "fqsen": "\\PluginHTML",
            "name": "PluginHTML",
            "summary": "HTML\u0020media\u0020handler",
            "url": "classes/PluginHTML.html"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003AreadStruct\u0028\u0029",
            "name": "readStruct",
            "summary": "Read\u0020structured\u0020data",
            "url": "classes/PluginHTML.html#method_readStruct"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003AmakeSource\u0028\u0029",
            "name": "makeSource",
            "summary": "Wraps\u0020metadata\u0020and\u0020HTML\u0020content",
            "url": "classes/PluginHTML.html#method_makeSource"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003ApreSave\u0028\u0029",
            "name": "preSave",
            "summary": "preSave\u0020event\u0020handler",
            "url": "classes/PluginHTML.html#method_preSave"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020event\u0020handler",
            "url": "classes/PluginHTML.html#method_read"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Edit\u0020event\u0020handler",
            "url": "classes/PluginHTML.html#method_edit"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginHTML.html#method_load"
        },                {
            "fqsen": "\\PluginHTML\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "var\u0020string",
            "url": "classes/PluginHTML.html#constant_VERSION"
        },                {
            "fqsen": "\\PluginIncludes",
            "name": "PluginIncludes",
            "summary": "PluginIncludes",
            "url": "classes/PluginIncludes.html"
        },                {
            "fqsen": "\\PluginIncludes\u003A\u003Amdx_include\u0028\u0029",
            "name": "mdx_include",
            "summary": "Include\u0020file\u0020implementation",
            "url": "classes/PluginIncludes.html#method_mdx_include"
        },                {
            "fqsen": "\\PluginIncludes\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginIncludes.html#method_load"
        },                {
            "fqsen": "\\PluginIncludes\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/PluginIncludes.html#constant_VERSION"
        },                {
            "fqsen": "\\ParsedownExtension",
            "name": "ParsedownExtension",
            "summary": "Further\u0020Extends\u0020Parsedown",
            "url": "classes/ParsedownExtension.html"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Version\u0020requirement\u0020check.",
            "url": "classes/ParsedownExtension.html#method___construct"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineForcedBr\u0028\u0029",
            "name": "inlineForcedBr",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineForcedBr"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineMarkedText\u0028\u0029",
            "name": "inlineMarkedText",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineMarkedText"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineSuperscript\u0028\u0029",
            "name": "inlineSuperscript",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineSuperscript"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineSubscript\u0028\u0029",
            "name": "inlineSubscript",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineSubscript"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineInsertedText\u0028\u0029",
            "name": "inlineInsertedText",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineInsertedText"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineKbdText\u0028\u0029",
            "name": "inlineKbdText",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineKbdText"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AblockTableComplete\u0028\u0029",
            "name": "blockTableComplete",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_blockTableComplete"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AblockFencedCodeComplete\u0028\u0029",
            "name": "blockFencedCodeComplete",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_blockFencedCodeComplete"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AblockHeader\u0028\u0029",
            "name": "blockHeader",
            "summary": "Heading\u0020process.",
            "url": "classes/ParsedownExtension.html#method_blockHeader"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AblockList\u0028\u0029",
            "name": "blockList",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_blockList"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AblockListContinue\u0028\u0029",
            "name": "blockListContinue",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_blockListContinue"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AblockListComplete\u0028\u0029",
            "name": "blockListComplete",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_blockListComplete"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AinlineLink\u0028\u0029",
            "name": "inlineLink",
            "summary": "",
            "url": "classes/ParsedownExtension.html#method_inlineLink"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/ParsedownExtension.html#constant_VERSION"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003A\u0024graphviz_modes",
            "name": "graphviz_modes",
            "summary": "",
            "url": "classes/ParsedownExtension.html#property_graphviz_modes"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003A\u0024headown",
            "name": "headown",
            "summary": "",
            "url": "classes/ParsedownExtension.html#property_headown"
        },                {
            "fqsen": "\\ParsedownExtension\u003A\u003A\u0024gfx_fmt",
            "name": "gfx_fmt",
            "summary": "",
            "url": "classes/ParsedownExtension.html#property_gfx_fmt"
        },                {
            "fqsen": "\\Parsedown",
            "name": "Parsedown",
            "summary": "Parsedown\nhttp\u003A\/\/parsedown.org",
            "url": "classes/Parsedown.html"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Atext\u0028\u0029",
            "name": "text",
            "summary": "",
            "url": "classes/Parsedown.html#method_text"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AsetBreaksEnabled\u0028\u0029",
            "name": "setBreaksEnabled",
            "summary": "",
            "url": "classes/Parsedown.html#method_setBreaksEnabled"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AsetMarkupEscaped\u0028\u0029",
            "name": "setMarkupEscaped",
            "summary": "",
            "url": "classes/Parsedown.html#method_setMarkupEscaped"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AsetUrlsLinked\u0028\u0029",
            "name": "setUrlsLinked",
            "summary": "",
            "url": "classes/Parsedown.html#method_setUrlsLinked"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AsetSafeMode\u0028\u0029",
            "name": "setSafeMode",
            "summary": "",
            "url": "classes/Parsedown.html#method_setSafeMode"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Alines\u0028\u0029",
            "name": "lines",
            "summary": "",
            "url": "classes/Parsedown.html#method_lines"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AisBlockContinuable\u0028\u0029",
            "name": "isBlockContinuable",
            "summary": "",
            "url": "classes/Parsedown.html#method_isBlockContinuable"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AisBlockCompletable\u0028\u0029",
            "name": "isBlockCompletable",
            "summary": "",
            "url": "classes/Parsedown.html#method_isBlockCompletable"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockCode\u0028\u0029",
            "name": "blockCode",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockCode"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockCodeContinue\u0028\u0029",
            "name": "blockCodeContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockCodeContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockCodeComplete\u0028\u0029",
            "name": "blockCodeComplete",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockCodeComplete"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockComment\u0028\u0029",
            "name": "blockComment",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockComment"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockCommentContinue\u0028\u0029",
            "name": "blockCommentContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockCommentContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockFencedCode\u0028\u0029",
            "name": "blockFencedCode",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockFencedCode"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockFencedCodeContinue\u0028\u0029",
            "name": "blockFencedCodeContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockFencedCodeContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockFencedCodeComplete\u0028\u0029",
            "name": "blockFencedCodeComplete",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockFencedCodeComplete"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockHeader\u0028\u0029",
            "name": "blockHeader",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockHeader"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockList\u0028\u0029",
            "name": "blockList",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockList"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockListContinue\u0028\u0029",
            "name": "blockListContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockListContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockListComplete\u0028\u0029",
            "name": "blockListComplete",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockListComplete"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockQuote\u0028\u0029",
            "name": "blockQuote",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockQuote"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockQuoteContinue\u0028\u0029",
            "name": "blockQuoteContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockQuoteContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockRule\u0028\u0029",
            "name": "blockRule",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockRule"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockSetextHeader\u0028\u0029",
            "name": "blockSetextHeader",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockSetextHeader"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockMarkup\u0028\u0029",
            "name": "blockMarkup",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockMarkup"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockMarkupContinue\u0028\u0029",
            "name": "blockMarkupContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockMarkupContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockReference\u0028\u0029",
            "name": "blockReference",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockReference"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockTable\u0028\u0029",
            "name": "blockTable",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockTable"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AblockTableContinue\u0028\u0029",
            "name": "blockTableContinue",
            "summary": "",
            "url": "classes/Parsedown.html#method_blockTableContinue"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aparagraph\u0028\u0029",
            "name": "paragraph",
            "summary": "",
            "url": "classes/Parsedown.html#method_paragraph"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aline\u0028\u0029",
            "name": "line",
            "summary": "",
            "url": "classes/Parsedown.html#method_line"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineCode\u0028\u0029",
            "name": "inlineCode",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineCode"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineEmailTag\u0028\u0029",
            "name": "inlineEmailTag",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineEmailTag"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineEmphasis\u0028\u0029",
            "name": "inlineEmphasis",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineEmphasis"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineEscapeSequence\u0028\u0029",
            "name": "inlineEscapeSequence",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineEscapeSequence"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineImage\u0028\u0029",
            "name": "inlineImage",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineImage"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineLink\u0028\u0029",
            "name": "inlineLink",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineLink"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineMarkup\u0028\u0029",
            "name": "inlineMarkup",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineMarkup"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineSpecialCharacter\u0028\u0029",
            "name": "inlineSpecialCharacter",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineSpecialCharacter"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineStrikethrough\u0028\u0029",
            "name": "inlineStrikethrough",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineStrikethrough"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineUrl\u0028\u0029",
            "name": "inlineUrl",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineUrl"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AinlineUrlTag\u0028\u0029",
            "name": "inlineUrlTag",
            "summary": "",
            "url": "classes/Parsedown.html#method_inlineUrlTag"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AunmarkedText\u0028\u0029",
            "name": "unmarkedText",
            "summary": "",
            "url": "classes/Parsedown.html#method_unmarkedText"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aelement\u0028\u0029",
            "name": "element",
            "summary": "",
            "url": "classes/Parsedown.html#method_element"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aelements\u0028\u0029",
            "name": "elements",
            "summary": "",
            "url": "classes/Parsedown.html#method_elements"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Ali\u0028\u0029",
            "name": "li",
            "summary": "",
            "url": "classes/Parsedown.html#method_li"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Parsedown.html#method_parse"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AsanitiseElement\u0028\u0029",
            "name": "sanitiseElement",
            "summary": "",
            "url": "classes/Parsedown.html#method_sanitiseElement"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AfilterUnsafeUrlInAttribute\u0028\u0029",
            "name": "filterUnsafeUrlInAttribute",
            "summary": "",
            "url": "classes/Parsedown.html#method_filterUnsafeUrlInAttribute"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aescape\u0028\u0029",
            "name": "escape",
            "summary": "",
            "url": "classes/Parsedown.html#method_escape"
        },                {
            "fqsen": "\\Parsedown\u003A\u003AstriAtStart\u0028\u0029",
            "name": "striAtStart",
            "summary": "",
            "url": "classes/Parsedown.html#method_striAtStart"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Ainstance\u0028\u0029",
            "name": "instance",
            "summary": "",
            "url": "classes/Parsedown.html#method_instance"
        },                {
            "fqsen": "\\Parsedown\u003A\u003Aversion",
            "name": "version",
            "summary": "",
            "url": "classes/Parsedown.html#constant_version"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024breaksEnabled",
            "name": "breaksEnabled",
            "summary": "",
            "url": "classes/Parsedown.html#property_breaksEnabled"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024markupEscaped",
            "name": "markupEscaped",
            "summary": "",
            "url": "classes/Parsedown.html#property_markupEscaped"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024urlsLinked",
            "name": "urlsLinked",
            "summary": "",
            "url": "classes/Parsedown.html#property_urlsLinked"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024safeMode",
            "name": "safeMode",
            "summary": "",
            "url": "classes/Parsedown.html#property_safeMode"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024safeLinksWhitelist",
            "name": "safeLinksWhitelist",
            "summary": "",
            "url": "classes/Parsedown.html#property_safeLinksWhitelist"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024BlockTypes",
            "name": "BlockTypes",
            "summary": "",
            "url": "classes/Parsedown.html#property_BlockTypes"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024unmarkedBlockTypes",
            "name": "unmarkedBlockTypes",
            "summary": "",
            "url": "classes/Parsedown.html#property_unmarkedBlockTypes"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024InlineTypes",
            "name": "InlineTypes",
            "summary": "",
            "url": "classes/Parsedown.html#property_InlineTypes"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024inlineMarkerList",
            "name": "inlineMarkerList",
            "summary": "",
            "url": "classes/Parsedown.html#property_inlineMarkerList"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024instances",
            "name": "instances",
            "summary": "",
            "url": "classes/Parsedown.html#property_instances"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024DefinitionData",
            "name": "DefinitionData",
            "summary": "",
            "url": "classes/Parsedown.html#property_DefinitionData"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024specialCharacters",
            "name": "specialCharacters",
            "summary": "",
            "url": "classes/Parsedown.html#property_specialCharacters"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024StrongRegex",
            "name": "StrongRegex",
            "summary": "",
            "url": "classes/Parsedown.html#property_StrongRegex"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024EmRegex",
            "name": "EmRegex",
            "summary": "",
            "url": "classes/Parsedown.html#property_EmRegex"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024regexHtmlAttribute",
            "name": "regexHtmlAttribute",
            "summary": "",
            "url": "classes/Parsedown.html#property_regexHtmlAttribute"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024voidElements",
            "name": "voidElements",
            "summary": "",
            "url": "classes/Parsedown.html#property_voidElements"
        },                {
            "fqsen": "\\Parsedown\u003A\u003A\u0024textLevelElements",
            "name": "textLevelElements",
            "summary": "",
            "url": "classes/Parsedown.html#property_textLevelElements"
        },                {
            "fqsen": "\\ParsedownExtra",
            "name": "ParsedownExtra",
            "summary": "Parsedown\u0020Extra\nhttps\u003A\/\/github.com\/erusev\/parsedown\u002Dextra",
            "url": "classes/ParsedownExtra.html"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method___construct"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003Atext\u0028\u0029",
            "name": "text",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_text"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockAbbreviation\u0028\u0029",
            "name": "blockAbbreviation",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockAbbreviation"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockFootnote\u0028\u0029",
            "name": "blockFootnote",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockFootnote"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockFootnoteContinue\u0028\u0029",
            "name": "blockFootnoteContinue",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockFootnoteContinue"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockFootnoteComplete\u0028\u0029",
            "name": "blockFootnoteComplete",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockFootnoteComplete"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockDefinitionList\u0028\u0029",
            "name": "blockDefinitionList",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockDefinitionList"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockDefinitionListContinue\u0028\u0029",
            "name": "blockDefinitionListContinue",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockDefinitionListContinue"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockHeader\u0028\u0029",
            "name": "blockHeader",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockHeader"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockMarkupComplete\u0028\u0029",
            "name": "blockMarkupComplete",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockMarkupComplete"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AblockSetextHeader\u0028\u0029",
            "name": "blockSetextHeader",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_blockSetextHeader"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AinlineFootnoteMarker\u0028\u0029",
            "name": "inlineFootnoteMarker",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_inlineFootnoteMarker"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AinlineLink\u0028\u0029",
            "name": "inlineLink",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_inlineLink"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AunmarkedText\u0028\u0029",
            "name": "unmarkedText",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_unmarkedText"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AaddDdElement\u0028\u0029",
            "name": "addDdElement",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_addDdElement"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AbuildFootnoteElement\u0028\u0029",
            "name": "buildFootnoteElement",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_buildFootnoteElement"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AparseAttributeData\u0028\u0029",
            "name": "parseAttributeData",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_parseAttributeData"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AprocessTag\u0028\u0029",
            "name": "processTag",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_processTag"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003AsortFootnotes\u0028\u0029",
            "name": "sortFootnotes",
            "summary": "",
            "url": "classes/ParsedownExtra.html#method_sortFootnotes"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003Aversion",
            "name": "version",
            "summary": "",
            "url": "classes/ParsedownExtra.html#constant_version"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003A\u0024footnoteCount",
            "name": "footnoteCount",
            "summary": "",
            "url": "classes/ParsedownExtra.html#property_footnoteCount"
        },                {
            "fqsen": "\\ParsedownExtra\u003A\u003A\u0024regexAttribute",
            "name": "regexAttribute",
            "summary": "",
            "url": "classes/ParsedownExtra.html#property_regexAttribute"
        },                {
            "fqsen": "\\DynamicParent",
            "name": "DynamicParent",
            "summary": "Parsedown\nhttp\u003A\/\/parsedown.org",
            "url": "classes/DynamicParent.html"
        },                {
            "fqsen": "\\DynamicParent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/DynamicParent.html#method___construct"
        },                {
            "fqsen": "\\ParsedownToC",
            "name": "ParsedownToC",
            "summary": "Implements\u0020ParsedowToC",
            "url": "classes/ParsedownToC.html"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Version\u0020requirement\u0020check.",
            "url": "classes/ParsedownToC.html#method___construct"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AblockHeader\u0028\u0029",
            "name": "blockHeader",
            "summary": "Heading\u0020process.",
            "url": "classes/ParsedownToC.html#method_blockHeader"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003Abody\u0028\u0029",
            "name": "body",
            "summary": "Parses\u0020the\u0020given\u0020markdown\u0020string\u0020to\u0020an\u0020HTML\u0020string\u0020but\u0020it\u0020leaves\u0020the\u0020ToC\ntag\u0020as\u0020is.\u0020It\u0027s\u0020an\u0020alias\u0020of\u0020the\u0020parent\u0020method\u0020\u0022\\DynamicParent\u003A\u003Atext\u0028\u0029\u0022.",
            "url": "classes/ParsedownToC.html#method_body"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AcontentsList\u0028\u0029",
            "name": "contentsList",
            "summary": "Returns\u0020the\u0020parsed\u0020ToC.",
            "url": "classes/ParsedownToC.html#method_contentsList"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AcreateAnchorID\u0028\u0029",
            "name": "createAnchorID",
            "summary": "Generates\u0020an\u0020anchor\u0020text\u0020that\u0020are\u0020link\u002Dable\u0020even\u0020the\u0020heading\u0020is\u0020not\u0020in\nASCII.",
            "url": "classes/ParsedownToC.html#method_createAnchorID"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AdecodeTagFromHash\u0028\u0029",
            "name": "decodeTagFromHash",
            "summary": "Decodes\u0020the\u0020hashed\u0020ToC\u0020tag\u0020to\u0020an\u0020original\u0020tag\u0020and\u0020replaces.",
            "url": "classes/ParsedownToC.html#method_decodeTagFromHash"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AencodeTagToHash\u0028\u0029",
            "name": "encodeTagToHash",
            "summary": "Encodes\u0020the\u0020ToC\u0020tag\u0020to\u0020a\u0020hashed\u0020tag\u0020and\u0020replace.",
            "url": "classes/ParsedownToC.html#method_encodeTagToHash"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AfetchText\u0028\u0029",
            "name": "fetchText",
            "summary": "Get\u0020only\u0020the\u0020text\u0020from\u0020a\u0020markdown\u0020string.",
            "url": "classes/ParsedownToC.html#method_fetchText"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AgetIdAttributeToC\u0028\u0029",
            "name": "getIdAttributeToC",
            "summary": "Gets\u0020the\u0020ID\u0020attribute\u0020of\u0020the\u0020ToC\u0020for\u0020HTML\u0020tags.",
            "url": "classes/ParsedownToC.html#method_getIdAttributeToC"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AgetSalt\u0028\u0029",
            "name": "getSalt",
            "summary": "Unique\u0020string\u0020to\u0020use\u0020as\u0020a\u0020salt\u0020value.",
            "url": "classes/ParsedownToC.html#method_getSalt"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AgetTagToC\u0028\u0029",
            "name": "getTagToC",
            "summary": "Gets\u0020the\u0020markdown\u0020tag\u0020for\u0020ToC.",
            "url": "classes/ParsedownToC.html#method_getTagToC"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AsetContentsList\u0028\u0029",
            "name": "setContentsList",
            "summary": "Set\/stores\u0020the\u0020heading\u0020block\u0020to\u0020ToC\u0020list\u0020in\u0020a\u0020string\u0020and\u0020array\u0020format.",
            "url": "classes/ParsedownToC.html#method_setContentsList"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AsetContentsListAsArray\u0028\u0029",
            "name": "setContentsListAsArray",
            "summary": "Sets\/stores\u0020the\u0020heading\u0020block\u0020info\u0020as\u0020an\u0020array.",
            "url": "classes/ParsedownToC.html#method_setContentsListAsArray"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AsetContentsListAsString\u0028\u0029",
            "name": "setContentsListAsString",
            "summary": "Sets\/stores\u0020the\u0020heading\u0020block\u0020info\u0020as\u0020a\u0020list\u0020in\u0020markdown\u0020format.",
            "url": "classes/ParsedownToC.html#method_setContentsListAsString"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AsetTagToc\u0028\u0029",
            "name": "setTagToc",
            "summary": "Sets\u0020the\u0020user\u0020defined\u0020ToC\u0020markdown\u0020tag.",
            "url": "classes/ParsedownToC.html#method_setTagToc"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003Atext\u0028\u0029",
            "name": "text",
            "summary": "Parses\u0020markdown\u0020string\u0020to\u0020HTML\u0020and\u0020also\u0020the\u0020\u0022\u005Btoc\u005D\u0022\u0020tag\u0020as\u0020well.",
            "url": "classes/ParsedownToC.html#method_text"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003Aversion",
            "name": "version",
            "summary": "\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\u002D\n\u0020Constants.",
            "url": "classes/ParsedownToC.html#constant_version"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AVERSION_PARSEDOWN_REQUIRED",
            "name": "VERSION_PARSEDOWN_REQUIRED",
            "summary": "",
            "url": "classes/ParsedownToC.html#constant_VERSION_PARSEDOWN_REQUIRED"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003ATAG_TOC_DEFAULT",
            "name": "TAG_TOC_DEFAULT",
            "summary": "",
            "url": "classes/ParsedownToC.html#constant_TAG_TOC_DEFAULT"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003AID_ATTRIBUTE_DEFAULT",
            "name": "ID_ATTRIBUTE_DEFAULT",
            "summary": "",
            "url": "classes/ParsedownToC.html#constant_ID_ATTRIBUTE_DEFAULT"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003A\u0024contentsListArray",
            "name": "contentsListArray",
            "summary": "",
            "url": "classes/ParsedownToC.html#property_contentsListArray"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003A\u0024contentsListString",
            "name": "contentsListString",
            "summary": "",
            "url": "classes/ParsedownToC.html#property_contentsListString"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003A\u0024firstHeadLevel",
            "name": "firstHeadLevel",
            "summary": "",
            "url": "classes/ParsedownToC.html#property_firstHeadLevel"
        },                {
            "fqsen": "\\ParsedownToC\u003A\u003A\u0024tag_toc",
            "name": "tag_toc",
            "summary": "",
            "url": "classes/ParsedownToC.html#property_tag_toc"
        },                {
            "fqsen": "\\PluginMarkdown",
            "name": "PluginMarkdown",
            "summary": "NacoWiki\u0020MarkDown",
            "url": "classes/PluginMarkdown.html"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003AreadStruct\u0028\u0029",
            "name": "readStruct",
            "summary": "Read\u0020structured\u0020data",
            "url": "classes/PluginMarkdown.html#method_readStruct"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003AmakeSource\u0028\u0029",
            "name": "makeSource",
            "summary": "Formats\u0020metadata\u0020and\u0020Markdown\u0020content",
            "url": "classes/PluginMarkdown.html#method_makeSource"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020event\u0020handler",
            "url": "classes/PluginMarkdown.html#method_render"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Edit\u0020event\u0020handler",
            "url": "classes/PluginMarkdown.html#method_edit"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003ApreSave\u0028\u0029",
            "name": "preSave",
            "summary": "preSave\u0020event\u0020handler",
            "url": "classes/PluginMarkdown.html#method_preSave"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020event\u0020handler",
            "url": "classes/PluginMarkdown.html#method_read"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginMarkdown.html#method_load"
        },                {
            "fqsen": "\\PluginMarkdown\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "var\u0020string",
            "url": "classes/PluginMarkdown.html#constant_VERSION"
        },                {
            "fqsen": "\\PluginVars",
            "name": "PluginVars",
            "summary": "NacoWiki\u0020Vars\u0020Plugin",
            "url": "classes/PluginVars.html"
        },                {
            "fqsen": "\\PluginVars\u003A\u003AdumpVars\u0028\u0029",
            "name": "dumpVars",
            "summary": "Dump\u0020global\u0020variables",
            "url": "classes/PluginVars.html#method_dumpVars"
        },                {
            "fqsen": "\\PluginVars\u003A\u003AdumpCfg\u0028\u0029",
            "name": "dumpCfg",
            "summary": "Dump\u0020config",
            "url": "classes/PluginVars.html#method_dumpCfg"
        },                {
            "fqsen": "\\PluginVars\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginVars.html#method_load"
        },                {
            "fqsen": "\\PluginVars\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "var\u0020string",
            "url": "classes/PluginVars.html#constant_VERSION"
        },                {
            "fqsen": "\\PluginWikiLinks",
            "name": "PluginWikiLinks",
            "summary": "Wiki\u0020style\u0020links",
            "url": "classes/PluginWikiLinks.html"
        },                {
            "fqsen": "\\PluginWikiLinks\u003A\u003AwikiLinks\u0028\u0029",
            "name": "wikiLinks",
            "summary": "WikiLinks\u0020implementation",
            "url": "classes/PluginWikiLinks.html#method_wikiLinks"
        },                {
            "fqsen": "\\PluginWikiLinks\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/PluginWikiLinks.html#method_load"
        },                {
            "fqsen": "\\PluginWikiLinks\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "var\u0020string",
            "url": "classes/PluginWikiLinks.html#constant_VERSION"
        },                {
            "fqsen": "\\PluginWikiLinks\u003A\u003A\u0024tree_cache",
            "name": "tree_cache",
            "summary": "file\u0020list\u0020cache\nvar\u0020string\u005B\u005D",
            "url": "classes/PluginWikiLinks.html#property_tree_cache"
        },                {
            "fqsen": "\\SiteGen",
            "name": "SiteGen",
            "summary": "Site\u0020generation",
            "url": "classes/SiteGen.html"
        },                {
            "fqsen": "\\SiteGen\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "Return\u0020this\u0020plugin\u0027s\u0020path",
            "url": "classes/SiteGen.html#method_path"
        },                {
            "fqsen": "\\SiteGen\u003A\u003ApostRender\u0028\u0029",
            "name": "postRender",
            "summary": "Fix\u0020generated\u0020links",
            "url": "classes/SiteGen.html#method_postRender"
        },                {
            "fqsen": "\\SiteGen\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020a\u0020wiki\u0020page\u0020as\u0020HTML",
            "url": "classes/SiteGen.html#method_render"
        },                {
            "fqsen": "\\SiteGen\u003A\u003Amkassets\u0028\u0029",
            "name": "mkassets",
            "summary": "Copy\u0020assets",
            "url": "classes/SiteGen.html#method_mkassets"
        },                {
            "fqsen": "\\SiteGen\u003A\u003Alst\u0028\u0029",
            "name": "lst",
            "summary": "List\u0020files",
            "url": "classes/SiteGen.html#method_lst"
        },                {
            "fqsen": "\\SiteGen\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/SiteGen.html#method_load"
        },                {
            "fqsen": "\\SiteGen\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "var\u0020string",
            "url": "classes/SiteGen.html#constant_VERSION"
        },                {
            "fqsen": "\\SiteGen\u003A\u003A\u0024exts",
            "name": "exts",
            "summary": "var\u0020string\u005B\u005D",
            "url": "classes/SiteGen.html#property_exts"
        },                {
            "fqsen": "\\YoutubeLinks",
            "name": "YoutubeLinks",
            "summary": "Shortocdes\u0020for\u0020youtube\u0020links",
            "url": "classes/YoutubeLinks.html"
        },                {
            "fqsen": "\\YoutubeLinks\u003A\u003AmakeLinks\u0028\u0029",
            "name": "makeLinks",
            "summary": "Youtube\u0020Links\u0020implementation",
            "url": "classes/YoutubeLinks.html#method_makeLinks"
        },                {
            "fqsen": "\\YoutubeLinks\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loading\u0020entry\u0020point\u0020for\u0020this\u0020class",
            "url": "classes/YoutubeLinks.html#method_load"
        },                {
            "fqsen": "\\YoutubeLinks\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "var\u0020string",
            "url": "classes/YoutubeLinks.html#constant_VERSION"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\NWiki",
            "name": "NWiki",
            "summary": "",
            "url": "namespaces/nwiki.html"
        }            ]
);
