name: static checks
on: [push]
jobs:
  job-id:
    runs-on: ubuntu-latest
    if: startswith(github.ref,'refs/heads/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: static checks
        run: |
          echo ${{ github.event_name }}
          checks=".ghrelease-checks"
          if [ -x  "$checks" ] ; then
            "$(readlink -f "$checks")" $@ || exit $?
          fi
